# The Docker image that will be used to build your app
image: alpine:latest

pages:
  script:
    - mkdir -p public
    - mv index.html scripts.js style.css assets public/

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH